# Form implementation generated from reading ui file 'D:\TAILIEUHOCTAPUEL\HK7_KỲ 1 NAM 3\TU DUY LAP TRINH T\TUDUYLAPTRINH_cntn\CHAPTER5\ex73\ui\MyMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 378)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 511, 311))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.formLayout_2)
        self.valueALabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.valueALabel.setObjectName("valueALabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.valueALabel)
        self.valueALineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.valueALineEdit.setObjectName("valueALineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.valueALineEdit)
        self.valueBLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.valueBLabel.setObjectName("valueBLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.valueBLabel)
        self.valueBLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.valueBLineEdit.setObjectName("valueBLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.valueBLineEdit)
        self.valueCLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.valueCLabel.setObjectName("valueCLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.valueCLabel)
        self.valueCLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.valueCLineEdit.setObjectName("valueCLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.valueCLineEdit)
        self.resultLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.resultLabel.setObjectName("resultLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.resultLabel)
        self.resultLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.resultLineEdit.setObjectName("resultLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.resultLineEdit)
        self.pushButton_calc = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton_calc)
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton_exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " GIAI PHUONG TRINH ax^2+bx+c=0"))
        self.valueALabel.setText(_translate("MainWindow", "Value A"))
        self.valueBLabel.setText(_translate("MainWindow", "Value B"))
        self.valueCLabel.setText(_translate("MainWindow", "Value C"))
        self.resultLabel.setText(_translate("MainWindow", "Result"))
        self.pushButton_calc.setText(_translate("MainWindow", "CALC"))
        self.pushButton_exit.setText(_translate("MainWindow", "EXIT"))
